# NumPy NoteBook Made By Abdelmalek Hissous
- Description : This is just a documentation about numpy

# importing Numpy As np

In [4]:
import numpy as np

# The Basics


In [5]:
# 1 Dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
# 2 Dim array
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# Get Dimension
dim = b.ndim
print(dim)

2


In [8]:
# get the shape of the N-Array
Shape = b.shape
print(Shape)

(2, 5)


In [9]:
# Get the type of the array
print(b.dtype)
# Change the type of the array to your choice
b = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype="int16")
print(b.dtype)

int64
int16


In [10]:
# Each Element size
print(b.itemsize)

2


In [11]:
# Total Size
print(b.nbytes)

20


# Accessing Elements And Changing Them

In [12]:
# 2d Array
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [13]:
# Accessing an Element ( Array[row,col] ) ( Python index starts from 0 )
print(a[1,0])

7


In [14]:
# Extracting a row
print(a[0,:])

[1 2 3 4 5 6]


In [15]:
# Extracting a col
print(a[:, 1])

[2 8]


In [16]:
# Fancy way to get data row example ( Array[row, start:end:step] )
print(a[0,1:4:2])

[2 4]


In [20]:
# Changing Data in An 2d array
a[0,0] = 0
print(a)

[[ 0  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [21]:
# Another way to change data (by row)
a[1,2:4] = [55,66]
print(a)

[[ 0  2  3  4  5  6]
 [ 7  8 55 66 11 12]]


In [22]:
# By col
a[:,2] = [22,33]
print(a)

[[ 0  2 22  4  5  6]
 [ 7  8 33 66 11 12]]


In [24]:
# 3d array example
c = np.array([[[1,2],[6,7]],[[8,9],[10,11]]])
print(c)

[[[ 1  2]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [26]:
# replacing a col
c[1,:,1] = [4,3]
print(c[1,:,1])

[4 3]


# Array Types

In [29]:
# Zero Array
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [66]:
# Ones Array
a = np.ones([3,4])
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [68]:
# Costum value array
a = np.full(a.shape, 4)
print(a)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [69]:
# random value (0-1)
a = np.random.rand(3,4)
print(a)

[[0.31032345 0.66433008 0.84727855 0.96632713]
 [0.1841333  0.26632254 0.59302788 0.70900121]
 [0.37363191 0.40165594 0.25151486 0.16175156]]


In [56]:
# random integer
a = np.random.randint(4,8,size=(3,4))
print(a)

[[6 6 7 7]
 [7 6 5 4]
 [7 4 6 5]]


In [62]:
# repeat array
a = np.array([[1,2,3,4,5]])
b = np.repeat(a, 3, axis=0)
print(b)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [34]:
# Identity Array
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Example :
- Making a 2d array using only the array types

In [70]:
e = np.ones([5,5])
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
e[1:4,1:4] = np.zeros([3,3])
print(e)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
e[2,2] = 9
print(e)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


- we couldev as well made the while 5x5 filled with ones then build another array with 9 in the middel and replace in the big array

#### IMPORTENT : IF YOU WANT TO COPY AN ARRAY USE THE METHODE .copy() UNLESS YOU WANT THE ABBILITY TO CHANGE THE ORIGNIAL FROM THE COPY


- Just Learned That you can print just by typing the variable name :)

# Mathmatics

In [81]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

# Basic Operations

In [80]:
# Element wise addition
b = a.copy()
a+b

array([2, 4, 6, 8])

In [83]:
# Multplication
a * 2

array([2, 4, 6, 8])

In [88]:
# Div
a / 2

array([0.5, 1. , 1.5, 2. ])

In [85]:
# Power
a ** 2

array([ 1,  4,  9, 16])

In [87]:
# Sin to each element
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### LINEAR ALGEBRA ( FUN STUFF ):)


In [104]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.ones((2,3))
print(a)
print(b)


[[1 2]
 [3 4]
 [5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [105]:
# Matrix mult
print(np.matmul(a, b))

[[ 3.  3.  3.]
 [ 7.  7.  7.]
 [11. 11. 11.]]


In [109]:
# Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [110]:
# Trace ( the sum of the diagonal elements
print(np.trace(c))

3.0


In [123]:
# Inverse
c = np.random.randint(2,7, size=(3,3))
print(c)
print(np.linalg.inv(c))

[[4 4 2]
 [6 4 4]
 [2 2 6]]
[[-0.4  0.5 -0.2]
 [ 0.7 -0.5  0.1]
 [-0.1  0.   0.2]]


In [124]:
# Norm (absolute value of a vector or matrix)
norm = np.linalg.norm(c)
print(norm)

12.165525060596439


In [126]:
# Eigenvalues and Eigenvectors ( An eigenvector is a special vector that dosebt change direction under a transformation it only gets stretched or shrunk
#The eigenvalue tells you how much it gets stretched or shrunk)
a = np.array([[2,0],[0,5]])
eigenvals, eigenvectors = np.linalg.eig(a)
print(eigenvals)
print(eigenvectors)

[2. 5.]
[[1. 0.]
 [0. 1.]]


In [127]:
# Rank
print(np.linalg.matrix_rank(a))


2


In [128]:
# Calculating Ax = b
b = np.array([5,4])
x = np.linalg.solve(a,b)
print(x)

[2.5 0.8]


# Statistics


In [140]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
# Min (You can specify axis 0 to work on col 1 for row)
a.min(axis=0)

array([1, 2, 3])

In [142]:
# Max (You can specify axis 0 to work on col 1 for row)
a.max(axis=0)

array([4, 5, 6])

In [143]:
# Sum
a.sum()

np.int64(21)

# ReShaping Arrays

In [156]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [155]:
# Changing the Shape Of an Array ( the new shape must have the same number of elements of the original array )
print(a.reshape(1,6))

[[1 2 3 4 5 6]]


In [158]:
# Vertically Stacking Vectors or Matrices
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack([a,b]))


[[1 2 3]
 [4 5 6]]


In [160]:
# Horizontally Stacking Vectors or Matrices
a = np.full((2,2),3)
b = np.full((2,2),2)
print(np.hstack([a,b]))

[[3 3 2 2]
 [3 3 2 2]]


# Usefull Stuff

In [168]:
# Loading Data From A File
data = np.genfromtxt('../../data/text.txt', delimiter=',')
data = data.astype("int32")
print(data)

[[ 57 132  89  12 178   6 199  43  90 154]
 [ 27  73 141 195   8 166  34 101  60   2]
 [149  37 117 200  11  75 163  93  19 123]]


# Masking And Advanced Indexing


In [171]:
print(data > 50)

[[ True  True  True False  True False  True False  True  True]
 [False  True  True  True False  True False  True  True False]
 [ True False  True  True False  True  True  True False  True]]


In [183]:
# You Can get the values that satisfies the condition (you can index with a list in numpy if it meets your condition)
# We can also use axis = 0 or 1 to check by row or by col ( 0 = col , 1 = row )
print(data[data > 50])
print(np.any(data >195, axis=1))

[ 57 132  89 178 199  90 154  73 141 195 166 101  60 149 117 200  75 163
  93 123]
[ True False  True]


In [185]:
print(((data > 50) & (data < 100)))

[[ True False  True False False False False False  True False]
 [False  True False False False False False False  True False]
 [False False False False False  True False  True False False]]


### IF There Is Anything Wrong In Here Please Let Me know
### Ill Be Adding More Commands Soon As Soon As I Learn Them